[package]
name = "iglo"
version = "0.1.0"
edition = "2021"


[dependencies]

[dev-dependencies.sdl2]
sdl2 = "0.36.0"
default-features = false
features = ["image", "ttf", "mixer"]

[dev-dependencies.rand]
rand = "0.8.5"

[lib]
name = "iglo"
path = "src/lib.rs"

[[example]]        
name = "iglo_ui"
path = "src/ui/main.rs"

[[example]]
name = "lookup_gen"
path = "src/engine/lookup_gens/main.rs"

[[example]]
name = "perft_debugger"
path = "src/dbg/perft_debugger.rs"