name: Build and Publish Docker Image
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version from Cargo.toml
      id: get_version
      run: |
        version=$(grep '^version' Cargo.toml | sed 's/.*"\(.*\)"/\1/')
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/iglo:${{ env.VERSION }} \
                     -t ghcr.io/${{ github.repository_owner }}/iglo:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/iglo:${{ env.VERSION }}
        docker push ghcr.io/${{ github.repository_owner }}/iglo:latest
